AWSTemplateFormatVersion: '2010-09-09'
Description: Example of processing messages on an SQS queue with Lambda
Resources:
  MySQSQueueFunction:
    Properties:
      CodeUri: s3://aws-davidiog-s3-general/de2382ae950475d029c66354a683c5e3
      Events:
        MySQSEvent:
          Properties:
            BatchSize: 10
            Queue:
              Fn::GetAtt:
              - MySqsQueue
              - Arn
          Type: SQS
      Handler: lambda-sqs.lambda_handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
  MySqsQueue:
    Type: AWS::SQS::Queue
Transform: AWS::Serverless-2016-10-31
